---
inherit_mode:
  merge:
    - Exclude
    - ExcludedMethods

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false